### PR TITLE
Mistral 7B model support

### PR DESCRIPTION
**Pull request by JianbangZ**
I added support to train the medusa heads for mistral-7b-instruct model and use for inference. There are several changes I made in order to support mistral
1. requires transformers==4.34, with this update it demands some changes to the llama code due to the tokenizer changes. so I added an modeling_mistral.py for mistral support, and modeling_llama_kv_434.py for llama support due to transofrmers 4.34 update
2. support GQA. this is straight forward with a fix in kv_cache.py. the KV cache dimension should be dependent on dim_key_value_heads instead of num_attention_heads.
3. other minor things 

I tested on llm-judge, with my own trained model (2 epoch on shareGPT), my MT-bench score is 6.66 (baseline is 6.84), though much better than llama2/vicuna models, it's still about 0.18 less than the mistral baseline model. I believe it's mostly because of using shareGPT data to finetune heads instead of the dataset used to train the mistral instruct model. So maybe switching to https://huggingface.co/datasets/lmsys/lmsys-chat-1m helps. Might also want to try austin-decoder to see if it improves. 

Belows are some wandb data to compare between the training data for mistral and vicuna 1.5 (purple), idk why, but the training curve for vicuna 1.5 is more "normal", maybe due to the dataset match, or maybe something else. Welcome any checks/fixs to improve this.
image
image

### CODE REVIEW

**Comment by leeyeehoo** [comment]
Hi Jim,

Thank you for the commit! We will take some time to process it.

**Comment by JianbangZ** [comment]
> Hi Jim,
> 
> Thank you for the commit! We will take some time to process it.

NP. I think also using a MLP block instead of a simple linear projection layer for the heads could be better, though will introduce more parameters. This was the one the findings from LLAVA 1.5

**Comment by louismullie** [comment]
@JianbangZ Thanks for this timely PR, and nice work. What data format did you use for the training run above? With `ShareGPT_Vicuna_unfiltered/ShareGPT_V4.3_unfiltered_cleaned_split.json` the train.py file fails on `assert conv.sep_style == SeparatorStyle.ADD_COLON_TWO`. (Works on main branch of this repository.)

**Comment by ctlllll** [comment]
Thank you guys for your contribution! We've added some Mistral models in the v1.0 version, so let me close the thread :)

**Pull request closed without merging**
